theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "contrast"
breadcrumbs: true
read_time: true
include: ["_pages"]
toc: true
logo: /media/qsharp-comm-logo.png
title: Q# Community
description: A space for community-driven projects and contrib libraries for Q#

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
